name: Hugo-CI
on:
  pull_request:
    branches: [ master ]

jobs:
  job-one:
    name: build
    runs-on: [self-hosted, linux, x64, dev4-barcode-cloud]
    steps:
      - name: hugo build
        run: |
          ls -la
